# ref: https://kubernetes.io/docs/concepts/configuration/overview/
  # namespace: ""
  # annotations: []
  # generateName: ""

# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
# kind: Deployment

apiVersion: v1
kind: Pod
metadata:
  name: express-rabbit-pod9
  labels:
    # name: express-rabbit-pod5
    app: web
spec:
  containers:
    # - name: key-value-store
    #   image: redis
    #   ports:
    #     - containerPort: 6379
    - name: frontend
      image: grimmer0125/express-rabbit
      imagePullPolicy: Never
      ports:
        - containerPort: 3000
# ----
# http://rafabene.com/2015/11/11/how-expose-kubernetes-services/
# apiVersion: v1
# kind: Service
# kind: ReplicationController

# kind: Endpoints https://kubernetes.io/docs/concepts/services-networking/service/
---
kind: Service
apiVersion: v1
metadata:
  name: my-service9
spec:
  selector:
    # name: express-rabbit-pod5
    app: web
  ports:
  - protocol: TCP
    port: 3000 # seems containerport
    # targetPort: 3001 # default: as port,? seems port on pod, NodePort is other than these two
  type: NodePort
